"""initial vocabulary tables

Revision ID: 3872c9d26720
Revises: 
Create Date: 2025-11-16 10:49:51.061987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3872c9d26720'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_text', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_text', 'language_code', name='uq_word_language')
    )
    op.create_index('idx_word_text_lower', 'words', ['word_text'], unique=False)
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_index(op.f('ix_words_language_code'), 'words', ['language_code'], unique=False)
    op.create_index(op.f('ix_words_word_text'), 'words', ['word_text'], unique=False)
    op.create_table('definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('definition_text', sa.Text(), nullable=False),
    sa.Column('part_of_speech', sa.Enum('NOUN', 'VERB', 'ADJECTIVE', 'ADVERB', 'PRONOUN', 'PREPOSITION', 'CONJUNCTION', 'INTERJECTION', 'DETERMINER', 'AUXILIARY', 'PHRASE', 'OTHER', name='partofspeech', native_enum=False, length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'order', name='uq_word_definition_order')
    )
    op.create_index('idx_definition_text', 'definitions', ['definition_text'], unique=False)
    op.create_index(op.f('ix_definitions_id'), 'definitions', ['id'], unique=False)
    op.create_index(op.f('ix_definitions_word_id'), 'definitions', ['word_id'], unique=False)
    op.create_table('word_relations',
    sa.Column('word_id_1', sa.Integer(), nullable=False),
    sa.Column('word_id_2', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('SYNONYM', 'ANTONYM', 'HYPERNYM', 'HYPONYM', 'MERONYM', 'HOLONYM', 'RELATED', name='relationtype', native_enum=False, length=50), nullable=False),
    sa.CheckConstraint('word_id_1 != word_id_2', name='ck_no_self_relation'),
    sa.ForeignKeyConstraint(['word_id_1'], ['words.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id_2'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id_1', 'word_id_2')
    )
    op.create_index('idx_word_relation', 'word_relations', ['word_id_1', 'word_id_2', 'relation_type'], unique=False)
    op.create_index(op.f('ix_word_relations_relation_type'), 'word_relations', ['relation_type'], unique=False)
    op.create_table('word_tags',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id', 'tag_id')
    )
    op.create_index('idx_word_tag', 'word_tags', ['word_id', 'tag_id'], unique=False)
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('example_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_example_text', 'examples', ['example_text'], unique=False)
    op.create_index(op.f('ix_examples_definition_id'), 'examples', ['definition_id'], unique=False)
    op.create_index(op.f('ix_examples_id'), 'examples', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examples_id'), table_name='examples')
    op.drop_index(op.f('ix_examples_definition_id'), table_name='examples')
    op.drop_index('idx_example_text', table_name='examples')
    op.drop_table('examples')
    op.drop_index('idx_word_tag', table_name='word_tags')
    op.drop_table('word_tags')
    op.drop_index(op.f('ix_word_relations_relation_type'), table_name='word_relations')
    op.drop_index('idx_word_relation', table_name='word_relations')
    op.drop_table('word_relations')
    op.drop_index(op.f('ix_definitions_word_id'), table_name='definitions')
    op.drop_index(op.f('ix_definitions_id'), table_name='definitions')
    op.drop_index('idx_definition_text', table_name='definitions')
    op.drop_table('definitions')
    op.drop_index(op.f('ix_words_word_text'), table_name='words')
    op.drop_index(op.f('ix_words_language_code'), table_name='words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_index('idx_word_text_lower', table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
