"""add word_forms table for inflections

Revision ID: abd75b163d91
Revises: f5079cc8f269
Create Date: 2025-11-30 19:14:29.790471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abd75b163d91"
down_revision: Union[str, Sequence[str], None] = "f5079cc8f269"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "word_forms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("form_text", sa.String(length=255), nullable=False),
        sa.Column("form_type", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["word_id"], ["words.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word_id", "form_text", name="uq_word_form"),
    )
    op.create_index("idx_form_text", "word_forms", ["form_text"], unique=False)
    op.create_index(
        op.f("ix_word_forms_form_text"), "word_forms", ["form_text"], unique=False
    )
    op.create_index(op.f("ix_word_forms_id"), "word_forms", ["id"], unique=False)
    op.create_index(
        op.f("ix_word_forms_word_id"), "word_forms", ["word_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_word_forms_word_id"), table_name="word_forms")
    op.drop_index(op.f("ix_word_forms_id"), table_name="word_forms")
    op.drop_index(op.f("ix_word_forms_form_text"), table_name="word_forms")
    op.drop_index("idx_form_text", table_name="word_forms")
    op.drop_table("word_forms")
    # ### end Alembic commands ###
